# Generated by Django 4.2.3 on 2023-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=12)),
                ('tipo', models.CharField(choices=[('I1', 'Item 1'), ('I2', 'Item 2'), ('I3', 'Item 3'), ('I4', 'Item 4')], max_length=2)),
                ('imagem', models.ImageField(upload_to='Itens/%Y/%m/%d')),
            ],
        ),
    ]
