# Generated by Django 4.2.3 on 2023-08-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_01', models.CharField(max_length=25)),
                ('produto_02', models.CharField(max_length=25)),
                ('produto_03', models.CharField(max_length=25)),
                ('tipo', models.CharField(choices=[('Tipo1', 'Tipo 1'), ('Tipo2', 'Tipo 2'), ('Tipo3', 'Tipo 3')], max_length=5)),
                ('imagem', models.ImageField(upload_to='produtos/%Y/%m/%d')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
