# Generated by Django 4.2.3 on 2023-08-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('Roupa M', 'Roupa Masculina'), ('Roupa F', 'Roupa Feminina'), ('Carros', 'Carros'), ('Motos', 'Motos'), ('Casa', 'Casa')], max_length=20)),
                ('imagem_produto', models.ImageField(upload_to='produtos/%Y/%m/%d')),
            ],
        ),
    ]
