# Generated by Django 4.2.3 on 2023-08-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exemplo18', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produtos',
            table='meu_nome_personalizado_da_tabela',
        ),
    ]
