# Generated by Django 4.2.3 on 2023-08-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exemplo18', '0003_alter_produtos_options_alter_produtos_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='categoria',
            field=models.CharField(choices=[('Roupa M', 'Roupa Masculina'), ('Roupa F', 'Roupa Feminina'), ('Carros', 'Carros'), ('Motos', 'Motos'), ('Casa', 'Casa')], max_length=7),
        ),
    ]
